version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: ebano_metabase
    hostname: metabase
    volumes:
      - ./metabase-data:/metabase-data
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: h2
      MB_DB_FILE: /metabase-data/metabase.db
    restart: unless-stopped
    networks:
      - ebano_network

networks:
  ebano_network:
    driver: bridge